HomeInventory/config/routes.rb
HomeInventory::Application.routes.draw do
  get "search/index"

  get "search/results"

  root :to => 'search#index'
  
  resources :items

  resources :boxes

  resources :locations

end

HomeInventory/app/models/box.rb
class Box < ActiveRecord::Base
  belongs_to :location
  has_many :items
end

HomeInventory/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :box
end

HomeInventory/app/models/location.rb
class Location < ActiveRecord::Base
  has_many :boxes
end

HomeInventory/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

HomeInventory/app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, :notice => 'Box was successfully created.' }
        format.json { render :json => @box, :status => :created, :location => @box }
      else
        format.html { render :action => "new" }
        format.json { render :json => @box.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, :notice => 'Box was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @box.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :ok }
    end
  end
end

HomeInventory/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, :notice => 'Item was successfully created.' }
        format.json { render :json => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, :notice => 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

HomeInventory/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, :notice => 'Location was successfully created.' }
        format.json { render :json => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, :notice => 'Location was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :ok }
    end
  end
end

HomeInventory/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = Item.search(params[:search])
    if params[:search] && !params[:search][:name_contains].blank?
      @items = @search.all
    end
  end

  def results
     
  end

end

HomeInventory/app/helpers/application_helper.rb
module ApplicationHelper
end

HomeInventory/app/helpers/boxes_helper.rb
module BoxesHelper
end

HomeInventory/app/helpers/items_helper.rb
module ItemsHelper
end

HomeInventory/app/helpers/locations_helper.rb
module LocationsHelper
end

HomeInventory/app/helpers/search_helper.rb
module SearchHelper
end

HomeInventory/app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.collection_select(:location_id, Location.all, :id, :name, {:include_blank => 'None'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HomeInventory/app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

HomeInventory/app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th></th>
    <th></th>
  </tr>

<% @boxes.each do |box| %>
  <tr>
    <td><%= link_to box.name, box %></td>
    <td><%= box.location.name %></td>
    <td><%= link_to 'Edit', edit_box_path(box) %></td>
    <td><%= link_to 'Destroy', box, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Box', new_box_path %>

HomeInventory/app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

HomeInventory/app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @box.id %>
</p>

<p>
  <b>Name:</b>
  <%= @box.name %>
</p>

<p>
  <b>Location:</b>
  <%= @box.location.name %>
</p>


<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

HomeInventory/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :box %><br />
    <%= f.collection_select(:box_id, Box.all, :id, :name, {:include_blank => 'None'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HomeInventory/app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

HomeInventory/app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Box</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.box %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

HomeInventory/app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

HomeInventory/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @item.id %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Box:</b>
  <%= @item.box %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

HomeInventory/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeInventory</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

HomeInventory/app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HomeInventory/app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

HomeInventory/app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.id %></td>
    <td><%= location.name %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

HomeInventory/app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

HomeInventory/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @location.id %>
</p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

HomeInventory/app/views/search/index.html.erb
<h1>Search</h1>
<%= form_for( @search, :url => { :controller => "search", :action => "index" }, :html => {:method => :get}) do |f|  %>
  <%= f.text_field :name_contains %>
  <%= f.submit %>
<% end %>

<% if @items %>
<% @items.each do |item| %>
<div>
  <h2><%= link_to item.name, item %></h2>
  <span><%= link_to item.box.name, item.box %>, <%= item.box.location.name %></span>
</div>
<% end %>
<% end %>

HomeInventory/app/views/search/results.html.erb
<h1>Search Results</h1>

<% @items.each do |item| %>
<div>
  <h2><%= item.name %></h2>
  <span><%= item.box.name %>, <%= item.box.location.name %></span>
</div>
<% end %>